---
title: "Nback task"
author: "Maria Polychronidou"
date: "3/3/2022"
output:
  html_document:
    toc: yes
    code_folding: hide
    toc_float:
      collapsed: no
      smooth_scroll: yes
    number_sections: yes
  word_document:
    toc: yes
  pdf_document:
    toc: yes
---



# Install packages 
```{r, results='hide'}
library("readxl")
library(dplyr)
library(ggplot2)
library(psycho)
library(tidyverse)
library(statsr)
library(psych)
```

# Import datasets
```{r, results='hide'}
library(readr)
Polym001_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym001_Nback experiment.txt")
Polym002_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym002_Nback experiment.txt")
Polym003_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym003_Nback experiment.txt")
Polym004_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym004_Nback experiment.txt")
Polym005_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym005_Nback experiment.txt")
Polym006_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym006_Nback experiment.txt")
Polym007_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym007_Nback experiment.txt")
Polym008_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym008_Nback experiment.txt")
Polym009_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym009_Nback experiment.txt")
Polym010_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym010_Nback experiment.txt")
Polym011_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym011_Nback experiment.txt")
Polym012_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym012_Nback experiment.txt")
Polym013_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym013_Nback experiment.txt")
Polym014_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym014_Nback experiment.txt")
Polym015_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym015_Nback experiment.txt")
Polym016_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym016_Nback experiment.txt")
Polym017_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym017_Nback experiment.txt")
Polym018_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym018_Nback experiment.txt")
Polym019_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym019_Nback experiment.txt")
Polym020_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym020_Nback experiment.txt")
Polym021_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym021_Nback experiment.txt")
Polym022_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym022_Nback experiment.txt")
Polym023_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym023_Nback experiment.txt")
Polym024_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym024_Nback experiment.txt")
Polym025_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym025_Nback experiment.txt")
Polym026_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym026_Nback experiment.txt")
Polym027_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym027_Nback experiment.txt")
Polym028_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym028_Nback experiment.txt")
Polym029_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym029_Nback experiment.txt")
Polym030_Nback <- read_csv("C:/Users/polyc/Desktop/THESIS/ANALYSIS/COGNITIVE TASKS/N-back txt files/Polym030_Nback experiment.txt")

```

# Merge data
```{r}
all_data <- rbind(Polym001_Nback, Polym002_Nback, Polym003_Nback, Polym004_Nback, Polym005_Nback, Polym006_Nback, Polym007_Nback, Polym008_Nback,Polym009_Nback, Polym010_Nback, Polym011_Nback, Polym012_Nback, Polym013_Nback,Polym014_Nback,Polym015_Nback, Polym016_Nback, Polym017_Nback, Polym018_Nback, Polym019_Nback, Polym020_Nback, Polym021_Nback, Polym022_Nback, Polym023_Nback, Polym024_Nback, Polym025_Nback, Polym026_Nback, Polym027_Nback, Polym028_Nback, Polym029_Nback, Polym030_Nback)

```

# Subset only the main trial
```{r}
dat <- subset(all_data, procedure=="MainProc")
```


# Define Factor Variables
```{r}
dat$procedure <- as.factor(dat$procedure)
dat$congruent <- as.factor(dat$congruent)
dat$corrAns <- as.factor(dat$corrAns)
dat$response.keys <- as.factor(dat$response.keys)
dat$participant <- as.factor(dat$participant)
dat$response.corr <- as.factor(dat$response.corr)
```


# Determine hits, misses, correct rejections, and false alarms

```{r}
dat <- dat %>% 
  mutate(hit = corrAns == "j" & response.keys == "j")%>%
  mutate(false_alarm = corrAns == "None" & response.keys == "j")%>%
  mutate(miss = corrAns == "j" & response.keys == "None")%>%
  mutate(correct_rejection = corrAns == "None" & response.keys == "None")
```


# Create a summary pivot table that captures counts
```{r}
dat2<-dat%>% 
  select(participant,hit,false_alarm,miss,correct_rejection)%>% 
  group_by(participant)%>% 
  summarize(n_hit=sum(hit),
            n_fa = sum(false_alarm),
            n_miss= sum(miss),
            n_cr = sum(correct_rejection))
print(dat2)
```


# Calculate d'

```{r}
# Psycho calculates d’, the beta, the A’ and the B’ based on the signal detection theory. Here is the documentation https://www.rdocumentation.org/packages/psycho/versions/0.5.0/topics/dprime

indices <- psycho::dprime(dat2$n_hit, dat2$n_fa, dat2$n_miss, dat2$n_cr)
dat2 <- cbind(dat2, indices)
```


# Calculate percentages
## Calculate proportion scores, such as overall accuracy.

```{r}
dat2 <- dat2 %>% 
  mutate(
    Overall_Accuracy = (n_hit+n_cr)/(n_hit+n_cr+n_fa+n_miss)
  )

dat2 <- dat2 %>% 
  mutate(
    p_hit = (n_hit)/(n_hit+n_miss)
  )

dat2 <- dat2 %>%  
  mutate(
    p_fa = (n_fa)/(n_fa+n_cr)
  )
dat2 <- dat2 %>% 
  mutate(
    p_miss = (n_miss)/(n_miss+n_hit)
  )
dat2 <- dat2 %>% 
  mutate(
    p_cr = (n_cr)/(n_cr+n_fa)
  ) 

summary(dat2)
```

# Calculate a'prime

```{r}
dat2$aprime
```

# Mean a'prime score
```{r}
dat3 <- dat2 %>%
  dplyr::select(participant,aprime)
dat3

describe(dat2$aprime)
```


```{r}
# exclude participant 13 because of very low score

dat3 <- dat3 %>%
  filter(participant != "Polym013")
dat3
```

# Save scores 

```{r}
saveRDS(dat3, file = "N-back_scores.rds", compress = "xz")
```







